#!/usr/bin/env python3
"""
MLB Standings Checker - Generated by Cloudera AI
🔒 This code was generated by Cloudera-hosted models only
🤖 Model: nvidia/llama-3.3-nemotron-super-49b-v1.5
🔒 Enterprise-grade AI processing
🚫 NO WINDSURF MODELS USED
"""

import requests
import json
from datetime import datetime
from typing import Dict, List, Optional

class MLBStandingsChecker:
    """MLB Standings Checker - Generated by Cloudera AI."""
    
    def __init__(self):
        """Initialize the MLB standings checker."""
        self.base_url = "https://statsapi.mlb.com/api/v1"
        self.current_year = datetime.now().year
        
    def get_standings(self, league_id: int, season: Optional[int] = None) -> Dict:
        """
        Get MLB standings for specified league and season.
        
        Args:
            league_id: League ID (103 for AL, 104 for NL)
            season: Season year (defaults to current year)
            
        Returns:
            Dictionary containing standings data
        """
        try:
            target_season = season or self.current_year
            
            # Get standings data
            url = f"{self.base_url}/standings"
            params = {
                'leagueId': league_id,
                'season': target_season,
                'standingsTypes': 'regularSeason'
            }
            
            response = requests.get(url, params=params, timeout=10)
            response.raise_for_status()
            
            data = response.json()
            return data.get('records', [])
            
        except requests.RequestException as e:
            print(f"❌ Error fetching MLB standings: {e}")
            return []
        except Exception as e:
            print(f"❌ Unexpected error: {e}")
            return []
    
    def get_all_mlb_standings(self, season: Optional[int] = None) -> Dict:
        """Get standings for both AL and NL."""
        target_season = season or self.current_year
        
        standings_data = {
            'season': target_season,
            'american_league': self.get_standings(103, target_season),
            'national_league': self.get_standings(104, target_season)
        }
        
        return standings_data
    
    def format_division_standings(self, division_data: Dict, league_name: str) -> None:
        """Format and display division standings."""
        if not division_data:
            return
        
        division_name = division_data.get('division', {}).get('nameFull', 'Unknown Division')
        team_records = division_data.get('teamRecords', [])
        
        if not team_records:
            return
        
        print(f"🏆 {league_name} - {division_name}")
        print("=" * 80)
        
        # Table header
        print(f"{'Pos':>3} | {'Team':<25} | {'W':>3} | {'L':>3} | {'PCT':>6} | {'GB':>4} | {'STRK':>5}")
        print("-" * 80)
        
        for i, team_record in enumerate(team_records, 1):
            team = team_record.get('team', {})
            
            team_name = team.get('name', 'Unknown')
            wins = team_record.get('wins', 0)
            losses = team_record.get('losses', 0)
            
            # Calculate winning percentage
            total_games = wins + losses
            pct = wins / total_games if total_games > 0 else 0.000
            
            # Games behind
            games_back = team_record.get('gamesBack', '0')
            
            # Streak
            streak = team_record.get('streak', {}).get('streakCode', '-')
            
            print(f"{i:>3} | {team_name:<25} | {wins:>3} | {losses:>3} | {pct:.3f} | {games_back:>4} | {streak:>5}")
    
    def format_league_standings(self, league_data: List, league_name: str) -> None:
        """Format and display league standings with wild card."""
        if not league_data:
            print(f"❌ No {league_name} data available")
            return
        
        print(f"🏆 {league_name} Standings")
        print("=" * 80)
        
        for division in league_data:
            self.format_division_standings(division, league_name)
            print()
    
    def get_team_schedule(self, team_id: int, season: Optional[int] = None) -> Dict:
        """Get team schedule for current season."""
        try:
            target_season = season or self.current_year
            
            url = f"{self.base_url}/schedule"
            params = {
                'sportId': 1,
                'teamId': team_id,
                'season': target_season
            }
            
            response = requests.get(url, params=params, timeout=10)
            response.raise_for_status()
            
            data = response.json()
            return data.get('dates', [])
            
        except requests.RequestException as e:
            print(f"❌ Error fetching team schedule: {e}")
            return []
        except Exception as e:
            print(f"❌ Unexpected error: {e}")
            return []
    
    def get_league_leaders(self, stat_type: str = 'homeRuns') -> Dict:
        """Get league leaders for specified stat category."""
        try:
            url = f"{self.base_url}/stats/leaders"
            params = {
                'statGroup': 'hitting',
                'season': self.current_year,
                'statType': stat_type,
                'limit': 10
            }
            
            response = requests.get(url, params=params, timeout=10)
            response.raise_for_status()
            
            data = response.json()
            return data.get('leagueLeaders', [])
            
        except requests.RequestException as e:
            print(f"❌ Error fetching league leaders: {e}")
            return []
        except Exception as e:
            print(f"❌ Unexpected error: {e}")
            return []

def main():
    """Main function - Generated by Cloudera AI."""
    print("⚾ MLB Standings Checker")
    print("🔒 Generated by Cloudera-hosted AI models ONLY")
    print("🚫 NO Windsurf models were used in generation")
    print("=" * 60)
    
    # Initialize the checker
    checker = MLBStandingsChecker()
    
    # Get current season standings
    current_year = datetime.now().year
    
    print(f"📊 Fetching MLB standings for {current_year}...")
    print()
    
    # Get all standings
    all_standings = checker.get_all_mlb_standings(current_year)
    
    # Display American League standings
    print("🏆 AMERICAN LEAGUE")
    print("=" * 80)
    checker.format_league_standings(all_standings['american_league'], "American League")
    
    print("\n" + "=" * 80)
    
    # Display National League standings
    print("🏆 NATIONAL LEAGUE")
    print("=" * 80)
    checker.format_league_standings(all_standings['national_league'], "National League")
    
    # Get league leaders (home runs)
    print("\n" + "=" * 80)
    print("🏅 HOME RUN LEADERS")
    print("=" * 60)
    
    hr_leaders = checker.get_league_leaders('homeRuns')
    if hr_leaders:
        print(f"{'Rank':>4} | {'Player':<25} | {'Team':<20} | {'HR':>3}")
        print("-" * 60)
        for i, leader in enumerate(hr_leaders, 1):
            person = leader.get('person', {})
            team = leader.get('team', {})
            stat = leader.get('stat', {})
            
            player_name = person.get('fullName', 'Unknown')
            team_name = team.get('name', 'Unknown')
            home_runs = stat.get('value', 0)
            
            print(f"{i:>4} | {player_name:<25} | {team_name:<20} | {home_runs:>3}")
    
    print("\n" + "=" * 80)
    print("🔒 Cloudera AI enterprise processing complete")
    print("📊 Data sourced from MLB Stats API")
    print("⚾ MLB™ is a trademark of Major League Baseball")

if __name__ == "__main__":
    main()