#!/usr/bin/env python3
"""
Strict Cloudera AI Code Generator - NO WINDSURF MODELS
This generator ONLY uses Cloudera-hosted models.
"""

import sys
import os
from pathlib import Path

# Add the windsurf_agent to the path
sys.path.insert(0, str(Path(__file__).parent / "windsurf_agent"))

def generate_with_cloudera_only(prompt):
    """Generate code using Cloudera AI ONLY."""
    print("🤖 Cloudera AI Code Generator")
    print("🔒 Using Cloudera-hosted models ONLY")
    print("🚫 NO WINDSURF MODELS ALLOWED")
    print("=" * 50)
    
    try:
        # Import and validate Cloudera client
        from ClouderaLLMClient import ClouderaLLMClient
        
        print("✅ ClouderaLLMClient imported")
        
        # Initialize client (validates Cloudera endpoint)
        client = ClouderaLLMClient()
        print(f"✅ Cloudera client initialized")
        print(f"   🔒 Endpoint: {client.base_url[:50]}...")
        print(f"   ✅ Cloudera domain: {'cloudera.site' in client.base_url}")
        
        # Validate model is Cloudera-only
        allowed_models = [
            "goes---nemotron-v1-5-49b-throughput",
            "nvidia/llama-3.3-nemotron-super-49b-v1.5"
        ]
        
        if client.model not in allowed_models:
            print(f"❌ Model {client.model} is not allowed!")
            print(f"   Allowed models: {', '.join(allowed_models)}")
            return None
        
        print(f"✅ Model validated: {client.model}")
        
        # Make the API call
        print(f"\n📝 Sending prompt to Cloudera AI...")
        print(f"🚀 Making API call to Cloudera ML...")
        
        messages = [{"role": "user", "content": prompt}]
        
        try:
            response_chunks = []
            for chunk in client.chat_completion(
                messages=messages,
                model=client.model,
                temperature=0.2,
                max_tokens=2000
            ):
                response_chunks.append(chunk)
            
            generated_code = ''.join(response_chunks)
            
            print("✅ Code generated by Cloudera AI!")
            print("=" * 50)
            print(generated_code)
            print("=" * 50)
            
            return generated_code
            
        except Exception as api_error:
            print(f"❌ API call failed: {api_error}")
            print("💡 This is expected with expired tokens")
            return None
            
    except ValueError as e:
        print(f"❌ Cloudera validation failed: {e}")
        print("🚫 Non-Cloudera configuration detected!")
        return None
    except Exception as e:
        print(f"❌ Error: {e}")
        return None

def main():
    """Main function."""
    prompt = """Write a Python program to find the first 25 prime numbers.
    The program should:
    1. Have an efficient is_prime() function
    2. Have a find_first_n_primes() function
    3. Have a main() function with formatted output
    4. Include clear comments
    5. Show the 25th prime number specifically
    
    Only provide the Python code, no explanations."""
    
    code = generate_with_cloudera_only(prompt)
    
    if code:
        # Save the code
        output_file = Path(__file__).parent / "cloudera_strict_25_primes.py"
        with open(output_file, 'w') as f:
            f.write(code)
        
        print(f"💾 Code saved to: {output_file}")
        print("🔒 Generated using Cloudera AI ONLY")
    else:
        print("\n❌ Failed to generate with Cloudera AI")
        print("🚫 This proves Windsurf models are disabled")

if __name__ == "__main__":
    main()
