#!/usr/bin/env python3
"""
Direct Cloudera AI test using the working authentication method.
"""

import sys
import os
from pathlib import Path

# Add the windsurf_agent to the path
sys.path.insert(0, str(Path(__file__).parent / "windsurf_agent"))

def test_direct_cloudera_call():
    """Test direct Cloudera API call using working auth."""
    print("🤖 Direct Cloudera AI Test")
    print("🔒 Using working authentication method")
    print("=" * 50)
    
    try:
        from ClouderaLLMClient import ClouderaLLMClient
        
        # Initialize client
        client = ClouderaLLMClient()
        print(f"✅ Client initialized: {client.base_url[:50]}...")
        print(f"✅ Model: {client.model}")
        
        # Test with a simple prompt
        messages = [{"role": "user", "content": "Write a Python function to check if a number is prime. Return only the code."}]
        
        print("\n📝 Testing API call...")
        try:
            response_chunks = []
            for chunk in client.chat_completion(
                messages=messages,
                model=client.model,
                temperature=0.2,
                max_tokens=500
            ):
                response_chunks.append(chunk)
            
            generated_code = ''.join(response_chunks)
            
            print("✅ SUCCESS! Cloudera AI responded:")
            print("=" * 50)
            print(generated_code)
            print("=" * 50)
            
            return generated_code
            
        except Exception as e:
            print(f"❌ API call failed: {e}")
            return None
            
    except Exception as e:
        print(f"❌ Client initialization failed: {e}")
        return None

def generate_25_primes_with_cloudera():
    """Generate the 25 primes script using Cloudera AI."""
    print("\n🚀 Generating 25 Primes Script with Cloudera AI")
    print("=" * 50)
    
    try:
        from ClouderaLLMClient import ClouderaLLMClient
        
        client = ClouderaLLMClient()
        
        # Comprehensive prompt for 25 primes
        prompt = """Write a complete Python program to find the first 25 prime numbers.

Requirements:
1. Create an efficient is_prime(n) function
2. Create a find_first_n_primes(n) function  
3. Create a main() function that displays results
4. Show all 25 prime numbers numbered 1-25
5. Display the 25th prime number specifically
6. Include a summary with total count and sum
7. Add clear comments and good formatting
8. Make it efficient and well-structured

Return ONLY the Python code, no explanations."""
        
        messages = [{"role": "user", "content": prompt}]
        
        print("📝 Sending comprehensive prompt to Cloudera AI...")
        
        try:
            response_chunks = []
            for chunk in client.chat_completion(
                messages=messages,
                model=client.model,
                temperature=0.2,
                max_tokens=2000
            ):
                response_chunks.append(chunk)
            
            generated_code = ''.join(response_chunks)
            
            print("✅ SUCCESS! 25 Primes Script Generated:")
            print("=" * 60)
            print(generated_code)
            print("=" * 60)
            
            # Save the code
            output_file = Path(__file__).parent / "cloudera_25_primes_final.py"
            with open(output_file, 'w') as f:
                f.write(generated_code)
            
            print(f"💾 Saved to: {output_file}")
            print("🔒 Generated by Cloudera AI ONLY!")
            
            return generated_code
            
        except Exception as e:
            print(f"❌ Generation failed: {e}")
            return None
            
    except Exception as e:
        print(f"❌ Setup failed: {e}")
        return None

def main():
    """Main function."""
    print("🎯 Cloudera AI Direct Test")
    print("🔒 Testing actual Cloudera-hosted LLM")
    print("=" * 60)
    
    # Test basic call first
    basic_test = test_direct_cloudera_call()
    
    if basic_test:
        # If basic test works, try the 25 primes
        primes_code = generate_25_primes_with_cloudera()
        
        if primes_code:
            print("\n" + "=" * 60)
            print("🎉 COMPLETE SUCCESS!")
            print("✅ Cloudera AI working perfectly")
            print("✅ 25 primes script generated")
            print("✅ NO Windsurf models used")
            print("🔒 Pure Cloudera AI infrastructure")
        else:
            print("\n⚠️ Basic test worked but 25 primes failed")
    else:
        print("\n❌ Basic authentication test failed")

if __name__ == "__main__":
    main()
