#!/usr/bin/env python3
"""
Generate a prime numbers program using Cloudera-hosted LLM.
"""

import sys
from pathlib import Path

# Add the windsurf_agent to the path
sys.path.insert(0, str(Path(__file__).parent / "windsurf_agent"))

try:
    from windsurf_agent.agent import WindsurfAgent
except ImportError as e:
    print(f"Import error: {e}")
    print("Make sure the windsurf_agent module is available")
    sys.exit(1)

def generate_prime_numbers_code():
    """Generate prime numbers code using Cloudera-hosted LLM."""
    print("🤖 Generating prime numbers code using Cloudera-hosted LLM...")
    print("=" * 60)
    
    try:
        # Initialize the agent with Cloudera AI only
        agent = WindsurfAgent()
        print("✅ Cloudera AI agent initialized successfully")
        
        # Prompt the Cloudera LLM to generate the prime numbers code
        prompt = """
        Write a Python program to find the first 10 prime numbers. 
        The program should:
        1. Have a function to check if a number is prime
        2. Have a function to find the first n prime numbers  
        3. Have a main function that displays the results
        4. Include clear comments and good formatting
        5. Be efficient and well-structured
        
        Only provide the Python code, no explanations.
        """
        
        print("🔍 Sending request to Cloudera AI...")
        response = agent.generate(prompt, temperature=0.2, max_tokens=1000)
        
        print("✅ Code generated successfully by Cloudera AI!")
        print("=" * 60)
        print("🤖 Generated Code:")
        print("=" * 60)
        print(response)
        print("=" * 60)
        
        # Save the generated code to a file
        output_file = Path(__file__).parent / "cloudera_generated_primes.py"
        with open(output_file, 'w') as f:
            f.write(response)
        
        print(f"💾 Code saved to: {output_file}")
        print("🔒 Generated using Cloudera-hosted AI models only")
        
        return response
        
    except Exception as e:
        print(f"❌ Error generating code with Cloudera AI: {e}")
        return None

def test_generated_code():
    """Test the generated code if it was created."""
    generated_file = Path(__file__).parent / "cloudera_generated_primes.py"
    
    if generated_file.exists():
        print("\n🧪 Testing the Cloudera-generated code...")
        print("=" * 60)
        
        try:
            # Run the generated code
            exec(open(generated_file).read())
            print("✅ Generated code executed successfully!")
        except Exception as e:
            print(f"❌ Error executing generated code: {e}")

def main():
    """Main function."""
    print("🚀 Cloudera AI Code Generation Demo")
    print("🔒 Using Cloudera-hosted models ONLY")
    print("=" * 60)
    
    # Generate code using Cloudera AI
    code = generate_prime_numbers_code()
    
    if code:
        # Test the generated code
        test_generated_code()
        
        print("\n" + "=" * 60)
        print("🎉 Summary:")
        print("✅ Code generated by Cloudera AI")
        print("✅ Only Cloudera endpoints used")
        print("✅ Model validation enforced")
        print("🔒 Enterprise-grade AI processing")
    else:
        print("❌ Failed to generate code")

if __name__ == "__main__":
    main()
